package com.sunrise.test.integration;

import static org.junit.jupiter.api.Assertions.*;
import java.time.LocalDate; import java.time.LocalTime; import java.util.List;
import org.junit.jupiter.api.*;
import com.sunrise.dao.*; import com.sunrise.model.*;

public class BillDAOIntegrationTest {
    private final BillDAO dao=new BillDAO(); private int patientId,dentistId,treatmentId,userId,appointmentId,billId; private String billNumber;
    @BeforeEach void setUp() throws Exception { DatabaseTestSupport.requireDatabase(); patientId=insertPatient(); dentistId=insertDentist(); treatmentId=insertTreatment(); userId=insertUser(); appointmentId=insertAppointment(); billNumber=DatabaseTestSupport.unique("BILL-TST"); Bill b=new Bill(billNumber,appointmentId,patientId,treatmentId,"APPOINTMENT",2500,5000,7500,userId); assertTrue(dao.addBill(b)); billId=DatabaseTestSupport.queryInt("SELECT bill_id FROM bills WHERE bill_number=?",billNumber); assertTrue(billId>0); }
    @AfterEach void tearDown() throws Exception { DatabaseTestSupport.execute("DELETE FROM bills WHERE bill_id=?",billId); DatabaseTestSupport.execute("DELETE FROM appointments WHERE appointment_id=?",appointmentId); DatabaseTestSupport.execute("DELETE FROM users WHERE user_id=?",userId); DatabaseTestSupport.execute("DELETE FROM treatments WHERE treatment_id=?",treatmentId); DatabaseTestSupport.execute("DELETE FROM dentists WHERE dentist_id=?",dentistId); DatabaseTestSupport.execute("DELETE FROM patients WHERE patient_id=?",patientId); }
    @Test void addBillCommitsAndCompletesAppointment() throws Exception { Bill b=dao.getBillById(billId); assertNotNull(b); assertEquals(7500,b.getTotalAmount()); assertEquals("COMPLETED",DatabaseTestSupport.queryString("SELECT status FROM appointments WHERE appointment_id=?",appointmentId)); }
    @Test void readAndSearchMethods() { assertTrue(dao.getAllBills().stream().anyMatch(b->b.getBillId()==billId)); assertEquals(billId,dao.getBillByAppointmentId(appointmentId).getBillId()); assertTrue(dao.getBillsByPatient(patientId).stream().anyMatch(b->b.getBillId()==billId)); assertTrue(dao.searchBills(billNumber,"ALL").stream().anyMatch(b->b.getBillId()==billId)); assertTrue(dao.searchBills(billNumber,"APPOINTMENT").stream().anyMatch(b->b.getBillId()==billId)); }
    @Test void duplicateChecksAndNextId() { assertTrue(dao.appointmentAlreadyBilled(appointmentId)); assertTrue(dao.billNumberExists(billNumber)); assertFalse(dao.billNumberExists(billNumber+"-missing")); assertTrue(dao.getNextBillId()>billId); }
    @Test void billCountIsPositive() { assertTrue(dao.getBillCount()>0); }
    @Test void missingBillReturnsNull() { assertNull(dao.getBillById(Integer.MAX_VALUE)); }
    private int insertPatient() throws Exception {String c=DatabaseTestSupport.unique("BILLPAT"); DatabaseTestSupport.execute("INSERT INTO patients(patient_code,name,address,contact_number,email) VALUES(?,?,?,?,?)",c,"Bill Test Patient","Address","0700000020",c+"@example.com"); return DatabaseTestSupport.queryInt("SELECT patient_id FROM patients WHERE patient_code=?",c);}
    private int insertDentist() throws Exception {String n=DatabaseTestSupport.unique("Bill Dentist"); DatabaseTestSupport.execute("INSERT INTO dentists(dentist_name,specialization,consultation_fee,phone_number,email,active) VALUES(?,?,?,?,?,?)",n,"General",2500,"0700000021",n.replace(" ","")+"@example.com",true); return DatabaseTestSupport.queryInt("SELECT dentist_id FROM dentists WHERE dentist_name=?",n);}
    private int insertTreatment() throws Exception {String n=DatabaseTestSupport.unique("Bill Treatment"); DatabaseTestSupport.execute("INSERT INTO treatments(treatment_name,description,treatment_fee,active) VALUES(?,?,?,?)",n,"Bill test",5000,true); return DatabaseTestSupport.queryInt("SELECT treatment_id FROM treatments WHERE treatment_name=?",n);}
    private int insertUser() throws Exception {String u=DatabaseTestSupport.unique("billuser"); DatabaseTestSupport.execute("INSERT INTO users(full_name,email,phone,address,position,username,password_hash,role,active,first_login) VALUES(?,?,?,?,?,?,?,?,?,?)","Bill Tester",u+"@example.com","0700000022","Address","Receptionist",u,"test-password","RECEPTIONIST",true,false); return DatabaseTestSupport.queryInt("SELECT user_id FROM users WHERE username=?",u);}
    private int insertAppointment() throws Exception {String n=DatabaseTestSupport.unique("BILLAPT"); DatabaseTestSupport.execute("INSERT INTO appointments(appointment_number,patient_id,dentist_id,treatment_id,appointment_date,appointment_time,status,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?)",n,patientId,dentistId,treatmentId,LocalDate.now().plusDays(15),LocalTime.of(14,0),"SCHEDULED","Bill test",userId); return DatabaseTestSupport.queryInt("SELECT appointment_id FROM appointments WHERE appointment_number=?",n);}
}
